/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorLogRouteImport } from './routes/visitor-log'
import { Route as VendorManagementRouteImport } from './routes/vendor-management'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TenantWorkbenchRouteImport } from './routes/tenant-workbench'
import { Route as TenantSuccessRouteImport } from './routes/tenant-success'
import { Route as TenantLifecycleRouteImport } from './routes/tenant-lifecycle'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SysAdminRouteImport } from './routes/sys-admin'
import { Route as SupportDeskRouteImport } from './routes/support-desk'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentWelfareRouteImport } from './routes/student-welfare'
import { Route as StrategicPlanRouteImport } from './routes/strategic-plan'
import { Route as StatusCenterRouteImport } from './routes/status-center'
import { Route as StaffDevelopmentRouteImport } from './routes/staff-development'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RiskRegisterRouteImport } from './routes/risk-register'
import { Route as RevenueOpsRouteImport } from './routes/revenue-ops'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as ReportCardRouteImport } from './routes/report-card'
import { Route as PtcRouteImport } from './routes/ptc'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PolicyLibraryRouteImport } from './routes/policy-library'
import { Route as PlatformOpsRouteImport } from './routes/platform-ops'
import { Route as PlatformConfigRouteImport } from './routes/platform-config'
import { Route as PlatformAuditRouteImport } from './routes/platform-audit'
import { Route as PlanCatalogRouteImport } from './routes/plan-catalog'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PaymentResultRouteImport } from './routes/payment-result'
import { Route as PartnerManagementRouteImport } from './routes/partner-management'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LostFoundRouteImport } from './routes/lost-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IncidentManagementRouteImport } from './routes/incident-management'
import { Route as HrRouteImport } from './routes/hr'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as FeeStructureRouteImport } from './routes/fee-structure'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as EnterpriseAnalyticsRouteImport } from './routes/enterprise-analytics'
import { Route as DutyRosterRouteImport } from './routes/duty-roster'
import { Route as DistrictManagementRouteImport } from './routes/district-management'
import { Route as DisciplineRouteImport } from './routes/discipline'
import { Route as DeveloperConsoleRouteImport } from './routes/developer-console'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DataGovernanceRouteImport } from './routes/data-governance'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as ContractCenterRouteImport } from './routes/contract-center'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CanteenRouteImport } from './routes/canteen'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BursariesRouteImport } from './routes/bursaries'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as ApprovalCenterRouteImport } from './routes/approval-center'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersStaffIdRouteImport } from './routes/teachers.$staffId'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as SSlugRouteImport } from './routes/s.$slug'

const VisitorLogRoute = VisitorLogRouteImport.update({
  id: '/visitor-log',
  path: '/visitor-log',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorManagementRoute = VendorManagementRouteImport.update({
  id: '/vendor-management',
  path: '/vendor-management',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantWorkbenchRoute = TenantWorkbenchRouteImport.update({
  id: '/tenant-workbench',
  path: '/tenant-workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSuccessRoute = TenantSuccessRouteImport.update({
  id: '/tenant-success',
  path: '/tenant-success',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLifecycleRoute = TenantLifecycleRouteImport.update({
  id: '/tenant-lifecycle',
  path: '/tenant-lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SysAdminRoute = SysAdminRouteImport.update({
  id: '/sys-admin',
  path: '/sys-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportDeskRoute = SupportDeskRouteImport.update({
  id: '/support-desk',
  path: '/support-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWelfareRoute = StudentWelfareRouteImport.update({
  id: '/student-welfare',
  path: '/student-welfare',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategicPlanRoute = StrategicPlanRouteImport.update({
  id: '/strategic-plan',
  path: '/strategic-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusCenterRoute = StatusCenterRouteImport.update({
  id: '/status-center',
  path: '/status-center',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDevelopmentRoute = StaffDevelopmentRouteImport.update({
  id: '/staff-development',
  path: '/staff-development',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRegisterRoute = RiskRegisterRouteImport.update({
  id: '/risk-register',
  path: '/risk-register',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueOpsRoute = RevenueOpsRouteImport.update({
  id: '/revenue-ops',
  path: '/revenue-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCardRoute = ReportCardRouteImport.update({
  id: '/report-card',
  path: '/report-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PtcRoute = PtcRouteImport.update({
  id: '/ptc',
  path: '/ptc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyLibraryRoute = PolicyLibraryRouteImport.update({
  id: '/policy-library',
  path: '/policy-library',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformOpsRoute = PlatformOpsRouteImport.update({
  id: '/platform-ops',
  path: '/platform-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformConfigRoute = PlatformConfigRouteImport.update({
  id: '/platform-config',
  path: '/platform-config',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAuditRoute = PlatformAuditRouteImport.update({
  id: '/platform-audit',
  path: '/platform-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanCatalogRoute = PlanCatalogRouteImport.update({
  id: '/plan-catalog',
  path: '/plan-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment-result',
  path: '/payment-result',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerManagementRoute = PartnerManagementRouteImport.update({
  id: '/partner-management',
  path: '/partner-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LostFoundRoute = LostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentManagementRoute = IncidentManagementRouteImport.update({
  id: '/incident-management',
  path: '/incident-management',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeStructureRoute = FeeStructureRouteImport.update({
  id: '/fee-structure',
  path: '/fee-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseAnalyticsRoute = EnterpriseAnalyticsRouteImport.update({
  id: '/enterprise-analytics',
  path: '/enterprise-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DutyRosterRoute = DutyRosterRouteImport.update({
  id: '/duty-roster',
  path: '/duty-roster',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictManagementRoute = DistrictManagementRouteImport.update({
  id: '/district-management',
  path: '/district-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineRoute = DisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperConsoleRoute = DeveloperConsoleRouteImport.update({
  id: '/developer-console',
  path: '/developer-console',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGovernanceRoute = DataGovernanceRouteImport.update({
  id: '/data-governance',
  path: '/data-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractCenterRoute = ContractCenterRouteImport.update({
  id: '/contract-center',
  path: '/contract-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CanteenRoute = CanteenRouteImport.update({
  id: '/canteen',
  path: '/canteen',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BursariesRoute = BursariesRouteImport.update({
  id: '/bursaries',
  path: '/bursaries',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalCenterRoute = ApprovalCenterRouteImport.update({
  id: '/approval-center',
  path: '/approval-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersStaffIdRoute = TeachersStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => TeachersRoute,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounting': typeof AccountingRoute
  '/activities': typeof ActivitiesRoute
  '/alumni': typeof AlumniRoute
  '/approval-center': typeof ApprovalCenterRoute
  '/assessments': typeof AssessmentsRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/backups': typeof BackupsRoute
  '/billing': typeof BillingRoute
  '/bursaries': typeof BursariesRoute
  '/calendar': typeof CalendarRoute
  '/canteen': typeof CanteenRoute
  '/classes': typeof ClassesRoute
  '/communication': typeof CommunicationRoute
  '/compliance': typeof ComplianceRoute
  '/contract-center': typeof ContractCenterRoute
  '/curriculum': typeof CurriculumRoute
  '/data-governance': typeof DataGovernanceRoute
  '/departments': typeof DepartmentsRoute
  '/developer-console': typeof DeveloperConsoleRoute
  '/discipline': typeof DisciplineRoute
  '/district-management': typeof DistrictManagementRoute
  '/duty-roster': typeof DutyRosterRoute
  '/enterprise-analytics': typeof EnterpriseAnalyticsRoute
  '/exams': typeof ExamsRoute
  '/facilities': typeof FacilitiesRoute
  '/fee-structure': typeof FeeStructureRoute
  '/fees': typeof FeesRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/hostel': typeof HostelRoute
  '/hr': typeof HrRoute
  '/incident-management': typeof IncidentManagementRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/lost-found': typeof LostFoundRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/partner-management': typeof PartnerManagementRoute
  '/payment-result': typeof PaymentResultRoute
  '/payroll': typeof PayrollRoute
  '/plan-catalog': typeof PlanCatalogRoute
  '/platform-audit': typeof PlatformAuditRoute
  '/platform-config': typeof PlatformConfigRoute
  '/platform-ops': typeof PlatformOpsRoute
  '/policy-library': typeof PolicyLibraryRoute
  '/procurement': typeof ProcurementRoute
  '/profile': typeof ProfileRoute
  '/ptc': typeof PtcRoute
  '/report-card': typeof ReportCardRoute
  '/reporting': typeof ReportingRoute
  '/reports': typeof ReportsRoute
  '/revenue-ops': typeof RevenueOpsRoute
  '/risk-register': typeof RiskRegisterRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/staff-development': typeof StaffDevelopmentRoute
  '/status-center': typeof StatusCenterRoute
  '/strategic-plan': typeof StrategicPlanRoute
  '/student-welfare': typeof StudentWelfareRoute
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRoute
  '/support-desk': typeof SupportDeskRoute
  '/sys-admin': typeof SysAdminRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/tenant-lifecycle': typeof TenantLifecycleRoute
  '/tenant-success': typeof TenantSuccessRoute
  '/tenant-workbench': typeof TenantWorkbenchRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/user-management': typeof UserManagementRoute
  '/vendor-management': typeof VendorManagementRoute
  '/visitor-log': typeof VisitorLogRoute
  '/s/$slug': typeof SSlugRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teachers/$staffId': typeof TeachersStaffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounting': typeof AccountingRoute
  '/activities': typeof ActivitiesRoute
  '/alumni': typeof AlumniRoute
  '/approval-center': typeof ApprovalCenterRoute
  '/assessments': typeof AssessmentsRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/backups': typeof BackupsRoute
  '/billing': typeof BillingRoute
  '/bursaries': typeof BursariesRoute
  '/calendar': typeof CalendarRoute
  '/canteen': typeof CanteenRoute
  '/classes': typeof ClassesRoute
  '/communication': typeof CommunicationRoute
  '/compliance': typeof ComplianceRoute
  '/contract-center': typeof ContractCenterRoute
  '/curriculum': typeof CurriculumRoute
  '/data-governance': typeof DataGovernanceRoute
  '/departments': typeof DepartmentsRoute
  '/developer-console': typeof DeveloperConsoleRoute
  '/discipline': typeof DisciplineRoute
  '/district-management': typeof DistrictManagementRoute
  '/duty-roster': typeof DutyRosterRoute
  '/enterprise-analytics': typeof EnterpriseAnalyticsRoute
  '/exams': typeof ExamsRoute
  '/facilities': typeof FacilitiesRoute
  '/fee-structure': typeof FeeStructureRoute
  '/fees': typeof FeesRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/hostel': typeof HostelRoute
  '/hr': typeof HrRoute
  '/incident-management': typeof IncidentManagementRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/lost-found': typeof LostFoundRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/partner-management': typeof PartnerManagementRoute
  '/payment-result': typeof PaymentResultRoute
  '/payroll': typeof PayrollRoute
  '/plan-catalog': typeof PlanCatalogRoute
  '/platform-audit': typeof PlatformAuditRoute
  '/platform-config': typeof PlatformConfigRoute
  '/platform-ops': typeof PlatformOpsRoute
  '/policy-library': typeof PolicyLibraryRoute
  '/procurement': typeof ProcurementRoute
  '/profile': typeof ProfileRoute
  '/ptc': typeof PtcRoute
  '/report-card': typeof ReportCardRoute
  '/reporting': typeof ReportingRoute
  '/reports': typeof ReportsRoute
  '/revenue-ops': typeof RevenueOpsRoute
  '/risk-register': typeof RiskRegisterRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/staff-development': typeof StaffDevelopmentRoute
  '/status-center': typeof StatusCenterRoute
  '/strategic-plan': typeof StrategicPlanRoute
  '/student-welfare': typeof StudentWelfareRoute
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRoute
  '/support-desk': typeof SupportDeskRoute
  '/sys-admin': typeof SysAdminRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/tenant-lifecycle': typeof TenantLifecycleRoute
  '/tenant-success': typeof TenantSuccessRoute
  '/tenant-workbench': typeof TenantWorkbenchRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/user-management': typeof UserManagementRoute
  '/vendor-management': typeof VendorManagementRoute
  '/visitor-log': typeof VisitorLogRoute
  '/s/$slug': typeof SSlugRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teachers/$staffId': typeof TeachersStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounting': typeof AccountingRoute
  '/activities': typeof ActivitiesRoute
  '/alumni': typeof AlumniRoute
  '/approval-center': typeof ApprovalCenterRoute
  '/assessments': typeof AssessmentsRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/backups': typeof BackupsRoute
  '/billing': typeof BillingRoute
  '/bursaries': typeof BursariesRoute
  '/calendar': typeof CalendarRoute
  '/canteen': typeof CanteenRoute
  '/classes': typeof ClassesRoute
  '/communication': typeof CommunicationRoute
  '/compliance': typeof ComplianceRoute
  '/contract-center': typeof ContractCenterRoute
  '/curriculum': typeof CurriculumRoute
  '/data-governance': typeof DataGovernanceRoute
  '/departments': typeof DepartmentsRoute
  '/developer-console': typeof DeveloperConsoleRoute
  '/discipline': typeof DisciplineRoute
  '/district-management': typeof DistrictManagementRoute
  '/duty-roster': typeof DutyRosterRoute
  '/enterprise-analytics': typeof EnterpriseAnalyticsRoute
  '/exams': typeof ExamsRoute
  '/facilities': typeof FacilitiesRoute
  '/fee-structure': typeof FeeStructureRoute
  '/fees': typeof FeesRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/hostel': typeof HostelRoute
  '/hr': typeof HrRoute
  '/incident-management': typeof IncidentManagementRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/lost-found': typeof LostFoundRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/parents': typeof ParentsRoute
  '/partner-management': typeof PartnerManagementRoute
  '/payment-result': typeof PaymentResultRoute
  '/payroll': typeof PayrollRoute
  '/plan-catalog': typeof PlanCatalogRoute
  '/platform-audit': typeof PlatformAuditRoute
  '/platform-config': typeof PlatformConfigRoute
  '/platform-ops': typeof PlatformOpsRoute
  '/policy-library': typeof PolicyLibraryRoute
  '/procurement': typeof ProcurementRoute
  '/profile': typeof ProfileRoute
  '/ptc': typeof PtcRoute
  '/report-card': typeof ReportCardRoute
  '/reporting': typeof ReportingRoute
  '/reports': typeof ReportsRoute
  '/revenue-ops': typeof RevenueOpsRoute
  '/risk-register': typeof RiskRegisterRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/staff-development': typeof StaffDevelopmentRoute
  '/status-center': typeof StatusCenterRoute
  '/strategic-plan': typeof StrategicPlanRoute
  '/student-welfare': typeof StudentWelfareRoute
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRoute
  '/support-desk': typeof SupportDeskRoute
  '/sys-admin': typeof SysAdminRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/tenant-lifecycle': typeof TenantLifecycleRoute
  '/tenant-success': typeof TenantSuccessRoute
  '/tenant-workbench': typeof TenantWorkbenchRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/user-management': typeof UserManagementRoute
  '/vendor-management': typeof VendorManagementRoute
  '/visitor-log': typeof VisitorLogRoute
  '/s/$slug': typeof SSlugRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/teachers/$staffId': typeof TeachersStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/accounting'
    | '/activities'
    | '/alumni'
    | '/approval-center'
    | '/assessments'
    | '/attendance'
    | '/audit'
    | '/backups'
    | '/billing'
    | '/bursaries'
    | '/calendar'
    | '/canteen'
    | '/classes'
    | '/communication'
    | '/compliance'
    | '/contract-center'
    | '/curriculum'
    | '/data-governance'
    | '/departments'
    | '/developer-console'
    | '/discipline'
    | '/district-management'
    | '/duty-roster'
    | '/enterprise-analytics'
    | '/exams'
    | '/facilities'
    | '/fee-structure'
    | '/fees'
    | '/health'
    | '/help'
    | '/hostel'
    | '/hr'
    | '/incident-management'
    | '/integrations'
    | '/inventory'
    | '/knowledge-base'
    | '/library'
    | '/login'
    | '/lost-found'
    | '/notifications'
    | '/onboarding'
    | '/parents'
    | '/partner-management'
    | '/payment-result'
    | '/payroll'
    | '/plan-catalog'
    | '/platform-audit'
    | '/platform-config'
    | '/platform-ops'
    | '/policy-library'
    | '/procurement'
    | '/profile'
    | '/ptc'
    | '/report-card'
    | '/reporting'
    | '/reports'
    | '/revenue-ops'
    | '/risk-register'
    | '/security'
    | '/settings'
    | '/staff-development'
    | '/status-center'
    | '/strategic-plan'
    | '/student-welfare'
    | '/students'
    | '/subjects'
    | '/support-desk'
    | '/sys-admin'
    | '/teachers'
    | '/tenant-lifecycle'
    | '/tenant-success'
    | '/tenant-workbench'
    | '/timetable'
    | '/transport'
    | '/user-management'
    | '/vendor-management'
    | '/visitor-log'
    | '/s/$slug'
    | '/students/$studentId'
    | '/teachers/$staffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/accounting'
    | '/activities'
    | '/alumni'
    | '/approval-center'
    | '/assessments'
    | '/attendance'
    | '/audit'
    | '/backups'
    | '/billing'
    | '/bursaries'
    | '/calendar'
    | '/canteen'
    | '/classes'
    | '/communication'
    | '/compliance'
    | '/contract-center'
    | '/curriculum'
    | '/data-governance'
    | '/departments'
    | '/developer-console'
    | '/discipline'
    | '/district-management'
    | '/duty-roster'
    | '/enterprise-analytics'
    | '/exams'
    | '/facilities'
    | '/fee-structure'
    | '/fees'
    | '/health'
    | '/help'
    | '/hostel'
    | '/hr'
    | '/incident-management'
    | '/integrations'
    | '/inventory'
    | '/knowledge-base'
    | '/library'
    | '/login'
    | '/lost-found'
    | '/notifications'
    | '/onboarding'
    | '/parents'
    | '/partner-management'
    | '/payment-result'
    | '/payroll'
    | '/plan-catalog'
    | '/platform-audit'
    | '/platform-config'
    | '/platform-ops'
    | '/policy-library'
    | '/procurement'
    | '/profile'
    | '/ptc'
    | '/report-card'
    | '/reporting'
    | '/reports'
    | '/revenue-ops'
    | '/risk-register'
    | '/security'
    | '/settings'
    | '/staff-development'
    | '/status-center'
    | '/strategic-plan'
    | '/student-welfare'
    | '/students'
    | '/subjects'
    | '/support-desk'
    | '/sys-admin'
    | '/teachers'
    | '/tenant-lifecycle'
    | '/tenant-success'
    | '/tenant-workbench'
    | '/timetable'
    | '/transport'
    | '/user-management'
    | '/vendor-management'
    | '/visitor-log'
    | '/s/$slug'
    | '/students/$studentId'
    | '/teachers/$staffId'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/accounting'
    | '/activities'
    | '/alumni'
    | '/approval-center'
    | '/assessments'
    | '/attendance'
    | '/audit'
    | '/backups'
    | '/billing'
    | '/bursaries'
    | '/calendar'
    | '/canteen'
    | '/classes'
    | '/communication'
    | '/compliance'
    | '/contract-center'
    | '/curriculum'
    | '/data-governance'
    | '/departments'
    | '/developer-console'
    | '/discipline'
    | '/district-management'
    | '/duty-roster'
    | '/enterprise-analytics'
    | '/exams'
    | '/facilities'
    | '/fee-structure'
    | '/fees'
    | '/health'
    | '/help'
    | '/hostel'
    | '/hr'
    | '/incident-management'
    | '/integrations'
    | '/inventory'
    | '/knowledge-base'
    | '/library'
    | '/login'
    | '/lost-found'
    | '/notifications'
    | '/onboarding'
    | '/parents'
    | '/partner-management'
    | '/payment-result'
    | '/payroll'
    | '/plan-catalog'
    | '/platform-audit'
    | '/platform-config'
    | '/platform-ops'
    | '/policy-library'
    | '/procurement'
    | '/profile'
    | '/ptc'
    | '/report-card'
    | '/reporting'
    | '/reports'
    | '/revenue-ops'
    | '/risk-register'
    | '/security'
    | '/settings'
    | '/staff-development'
    | '/status-center'
    | '/strategic-plan'
    | '/student-welfare'
    | '/students'
    | '/subjects'
    | '/support-desk'
    | '/sys-admin'
    | '/teachers'
    | '/tenant-lifecycle'
    | '/tenant-success'
    | '/tenant-workbench'
    | '/timetable'
    | '/transport'
    | '/user-management'
    | '/vendor-management'
    | '/visitor-log'
    | '/s/$slug'
    | '/students/$studentId'
    | '/teachers/$staffId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AccountingRoute: typeof AccountingRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AlumniRoute: typeof AlumniRoute
  ApprovalCenterRoute: typeof ApprovalCenterRoute
  AssessmentsRoute: typeof AssessmentsRoute
  AttendanceRoute: typeof AttendanceRoute
  AuditRoute: typeof AuditRoute
  BackupsRoute: typeof BackupsRoute
  BillingRoute: typeof BillingRoute
  BursariesRoute: typeof BursariesRoute
  CalendarRoute: typeof CalendarRoute
  CanteenRoute: typeof CanteenRoute
  ClassesRoute: typeof ClassesRoute
  CommunicationRoute: typeof CommunicationRoute
  ComplianceRoute: typeof ComplianceRoute
  ContractCenterRoute: typeof ContractCenterRoute
  CurriculumRoute: typeof CurriculumRoute
  DataGovernanceRoute: typeof DataGovernanceRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DeveloperConsoleRoute: typeof DeveloperConsoleRoute
  DisciplineRoute: typeof DisciplineRoute
  DistrictManagementRoute: typeof DistrictManagementRoute
  DutyRosterRoute: typeof DutyRosterRoute
  EnterpriseAnalyticsRoute: typeof EnterpriseAnalyticsRoute
  ExamsRoute: typeof ExamsRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FeeStructureRoute: typeof FeeStructureRoute
  FeesRoute: typeof FeesRoute
  HealthRoute: typeof HealthRoute
  HelpRoute: typeof HelpRoute
  HostelRoute: typeof HostelRoute
  HrRoute: typeof HrRoute
  IncidentManagementRoute: typeof IncidentManagementRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InventoryRoute: typeof InventoryRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  LostFoundRoute: typeof LostFoundRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentsRoute: typeof ParentsRoute
  PartnerManagementRoute: typeof PartnerManagementRoute
  PaymentResultRoute: typeof PaymentResultRoute
  PayrollRoute: typeof PayrollRoute
  PlanCatalogRoute: typeof PlanCatalogRoute
  PlatformAuditRoute: typeof PlatformAuditRoute
  PlatformConfigRoute: typeof PlatformConfigRoute
  PlatformOpsRoute: typeof PlatformOpsRoute
  PolicyLibraryRoute: typeof PolicyLibraryRoute
  ProcurementRoute: typeof ProcurementRoute
  ProfileRoute: typeof ProfileRoute
  PtcRoute: typeof PtcRoute
  ReportCardRoute: typeof ReportCardRoute
  ReportingRoute: typeof ReportingRoute
  ReportsRoute: typeof ReportsRoute
  RevenueOpsRoute: typeof RevenueOpsRoute
  RiskRegisterRoute: typeof RiskRegisterRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  StaffDevelopmentRoute: typeof StaffDevelopmentRoute
  StatusCenterRoute: typeof StatusCenterRoute
  StrategicPlanRoute: typeof StrategicPlanRoute
  StudentWelfareRoute: typeof StudentWelfareRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  SubjectsRoute: typeof SubjectsRoute
  SupportDeskRoute: typeof SupportDeskRoute
  SysAdminRoute: typeof SysAdminRoute
  TeachersRoute: typeof TeachersRouteWithChildren
  TenantLifecycleRoute: typeof TenantLifecycleRoute
  TenantSuccessRoute: typeof TenantSuccessRoute
  TenantWorkbenchRoute: typeof TenantWorkbenchRoute
  TimetableRoute: typeof TimetableRoute
  TransportRoute: typeof TransportRoute
  UserManagementRoute: typeof UserManagementRoute
  VendorManagementRoute: typeof VendorManagementRoute
  VisitorLogRoute: typeof VisitorLogRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitor-log': {
      id: '/visitor-log'
      path: '/visitor-log'
      fullPath: '/visitor-log'
      preLoaderRoute: typeof VisitorLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-management': {
      id: '/vendor-management'
      path: '/vendor-management'
      fullPath: '/vendor-management'
      preLoaderRoute: typeof VendorManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-workbench': {
      id: '/tenant-workbench'
      path: '/tenant-workbench'
      fullPath: '/tenant-workbench'
      preLoaderRoute: typeof TenantWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-success': {
      id: '/tenant-success'
      path: '/tenant-success'
      fullPath: '/tenant-success'
      preLoaderRoute: typeof TenantSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant-lifecycle': {
      id: '/tenant-lifecycle'
      path: '/tenant-lifecycle'
      fullPath: '/tenant-lifecycle'
      preLoaderRoute: typeof TenantLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sys-admin': {
      id: '/sys-admin'
      path: '/sys-admin'
      fullPath: '/sys-admin'
      preLoaderRoute: typeof SysAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-desk': {
      id: '/support-desk'
      path: '/support-desk'
      fullPath: '/support-desk'
      preLoaderRoute: typeof SupportDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-welfare': {
      id: '/student-welfare'
      path: '/student-welfare'
      fullPath: '/student-welfare'
      preLoaderRoute: typeof StudentWelfareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategic-plan': {
      id: '/strategic-plan'
      path: '/strategic-plan'
      fullPath: '/strategic-plan'
      preLoaderRoute: typeof StrategicPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status-center': {
      id: '/status-center'
      path: '/status-center'
      fullPath: '/status-center'
      preLoaderRoute: typeof StatusCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-development': {
      id: '/staff-development'
      path: '/staff-development'
      fullPath: '/staff-development'
      preLoaderRoute: typeof StaffDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-register': {
      id: '/risk-register'
      path: '/risk-register'
      fullPath: '/risk-register'
      preLoaderRoute: typeof RiskRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue-ops': {
      id: '/revenue-ops'
      path: '/revenue-ops'
      fullPath: '/revenue-ops'
      preLoaderRoute: typeof RevenueOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-card': {
      id: '/report-card'
      path: '/report-card'
      fullPath: '/report-card'
      preLoaderRoute: typeof ReportCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptc': {
      id: '/ptc'
      path: '/ptc'
      fullPath: '/ptc'
      preLoaderRoute: typeof PtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-library': {
      id: '/policy-library'
      path: '/policy-library'
      fullPath: '/policy-library'
      preLoaderRoute: typeof PolicyLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-ops': {
      id: '/platform-ops'
      path: '/platform-ops'
      fullPath: '/platform-ops'
      preLoaderRoute: typeof PlatformOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-config': {
      id: '/platform-config'
      path: '/platform-config'
      fullPath: '/platform-config'
      preLoaderRoute: typeof PlatformConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-audit': {
      id: '/platform-audit'
      path: '/platform-audit'
      fullPath: '/platform-audit'
      preLoaderRoute: typeof PlatformAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-catalog': {
      id: '/plan-catalog'
      path: '/plan-catalog'
      fullPath: '/plan-catalog'
      preLoaderRoute: typeof PlanCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-result': {
      id: '/payment-result'
      path: '/payment-result'
      fullPath: '/payment-result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-management': {
      id: '/partner-management'
      path: '/partner-management'
      fullPath: '/partner-management'
      preLoaderRoute: typeof PartnerManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-found': {
      id: '/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof LostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident-management': {
      id: '/incident-management'
      path: '/incident-management'
      fullPath: '/incident-management'
      preLoaderRoute: typeof IncidentManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-structure': {
      id: '/fee-structure'
      path: '/fee-structure'
      fullPath: '/fee-structure'
      preLoaderRoute: typeof FeeStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-analytics': {
      id: '/enterprise-analytics'
      path: '/enterprise-analytics'
      fullPath: '/enterprise-analytics'
      preLoaderRoute: typeof EnterpriseAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duty-roster': {
      id: '/duty-roster'
      path: '/duty-roster'
      fullPath: '/duty-roster'
      preLoaderRoute: typeof DutyRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district-management': {
      id: '/district-management'
      path: '/district-management'
      fullPath: '/district-management'
      preLoaderRoute: typeof DistrictManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline': {
      id: '/discipline'
      path: '/discipline'
      fullPath: '/discipline'
      preLoaderRoute: typeof DisciplineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-console': {
      id: '/developer-console'
      path: '/developer-console'
      fullPath: '/developer-console'
      preLoaderRoute: typeof DeveloperConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-governance': {
      id: '/data-governance'
      path: '/data-governance'
      fullPath: '/data-governance'
      preLoaderRoute: typeof DataGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract-center': {
      id: '/contract-center'
      path: '/contract-center'
      fullPath: '/contract-center'
      preLoaderRoute: typeof ContractCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canteen': {
      id: '/canteen'
      path: '/canteen'
      fullPath: '/canteen'
      preLoaderRoute: typeof CanteenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bursaries': {
      id: '/bursaries'
      path: '/bursaries'
      fullPath: '/bursaries'
      preLoaderRoute: typeof BursariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval-center': {
      id: '/approval-center'
      path: '/approval-center'
      fullPath: '/approval-center'
      preLoaderRoute: typeof ApprovalCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$staffId': {
      id: '/teachers/$staffId'
      path: '/$staffId'
      fullPath: '/teachers/$staffId'
      preLoaderRoute: typeof TeachersStaffIdRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentsRouteChildren {
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsStudentIdRoute: StudentsStudentIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface TeachersRouteChildren {
  TeachersStaffIdRoute: typeof TeachersStaffIdRoute
}

const TeachersRouteChildren: TeachersRouteChildren = {
  TeachersStaffIdRoute: TeachersStaffIdRoute,
}

const TeachersRouteWithChildren = TeachersRoute._addFileChildren(
  TeachersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AccountingRoute: AccountingRoute,
  ActivitiesRoute: ActivitiesRoute,
  AlumniRoute: AlumniRoute,
  ApprovalCenterRoute: ApprovalCenterRoute,
  AssessmentsRoute: AssessmentsRoute,
  AttendanceRoute: AttendanceRoute,
  AuditRoute: AuditRoute,
  BackupsRoute: BackupsRoute,
  BillingRoute: BillingRoute,
  BursariesRoute: BursariesRoute,
  CalendarRoute: CalendarRoute,
  CanteenRoute: CanteenRoute,
  ClassesRoute: ClassesRoute,
  CommunicationRoute: CommunicationRoute,
  ComplianceRoute: ComplianceRoute,
  ContractCenterRoute: ContractCenterRoute,
  CurriculumRoute: CurriculumRoute,
  DataGovernanceRoute: DataGovernanceRoute,
  DepartmentsRoute: DepartmentsRoute,
  DeveloperConsoleRoute: DeveloperConsoleRoute,
  DisciplineRoute: DisciplineRoute,
  DistrictManagementRoute: DistrictManagementRoute,
  DutyRosterRoute: DutyRosterRoute,
  EnterpriseAnalyticsRoute: EnterpriseAnalyticsRoute,
  ExamsRoute: ExamsRoute,
  FacilitiesRoute: FacilitiesRoute,
  FeeStructureRoute: FeeStructureRoute,
  FeesRoute: FeesRoute,
  HealthRoute: HealthRoute,
  HelpRoute: HelpRoute,
  HostelRoute: HostelRoute,
  HrRoute: HrRoute,
  IncidentManagementRoute: IncidentManagementRoute,
  IntegrationsRoute: IntegrationsRoute,
  InventoryRoute: InventoryRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  LostFoundRoute: LostFoundRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ParentsRoute: ParentsRoute,
  PartnerManagementRoute: PartnerManagementRoute,
  PaymentResultRoute: PaymentResultRoute,
  PayrollRoute: PayrollRoute,
  PlanCatalogRoute: PlanCatalogRoute,
  PlatformAuditRoute: PlatformAuditRoute,
  PlatformConfigRoute: PlatformConfigRoute,
  PlatformOpsRoute: PlatformOpsRoute,
  PolicyLibraryRoute: PolicyLibraryRoute,
  ProcurementRoute: ProcurementRoute,
  ProfileRoute: ProfileRoute,
  PtcRoute: PtcRoute,
  ReportCardRoute: ReportCardRoute,
  ReportingRoute: ReportingRoute,
  ReportsRoute: ReportsRoute,
  RevenueOpsRoute: RevenueOpsRoute,
  RiskRegisterRoute: RiskRegisterRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  StaffDevelopmentRoute: StaffDevelopmentRoute,
  StatusCenterRoute: StatusCenterRoute,
  StrategicPlanRoute: StrategicPlanRoute,
  StudentWelfareRoute: StudentWelfareRoute,
  StudentsRoute: StudentsRouteWithChildren,
  SubjectsRoute: SubjectsRoute,
  SupportDeskRoute: SupportDeskRoute,
  SysAdminRoute: SysAdminRoute,
  TeachersRoute: TeachersRouteWithChildren,
  TenantLifecycleRoute: TenantLifecycleRoute,
  TenantSuccessRoute: TenantSuccessRoute,
  TenantWorkbenchRoute: TenantWorkbenchRoute,
  TimetableRoute: TimetableRoute,
  TransportRoute: TransportRoute,
  UserManagementRoute: UserManagementRoute,
  VendorManagementRoute: VendorManagementRoute,
  VisitorLogRoute: VisitorLogRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
